### ISSUE TITLE
Connecting to Ethereum Wallet

### ISSUE THREAD

**Issue by joshterrill** [gmtDevs/atom-ethereum-interface#15]
Hello, how can I connect this to Ethereum Wallet while ethereum wallet is open on the testnet?

**Comment by CyberNano** [comment]
Try this: geth --testnet --rpc --rpcapi="db,eth,net,web3,personal" --rpcport "8545" --rpcaddr "127.0.0.1" --rpccorsdomain "localhost" console

**Comment by 0mkara** [comment]
@joshterrill hope connecting to geth instance is not a problem any more.
