### ISSUE TITLE
Can't Get It Working - Not Connecting to local Geth 

### ISSUE THREAD

**Issue by always-sunny** [gmtDevs/atom-ethereum-interface#6]
1. I downloaded atom
2. Downloaded atom-ethereum-interface, and put that folder into atom.app
3. It's not showing up on packages. 
4. I attempted to download the interface from source 
5. I used _git clone https://github.com/gmtcreators/atom..._ 
6. Destination path already exists and isn't empty
7. I cd into atom-ethereum-interface and then do **git branch dev**
8. I receive **fatal: not a git repository (or any of the parent directories): .git**
9. lib/ethereum-interface.coffee already exists in my folder and when I do the vi command I just get stuck in the vi console
10. The biggest problem I have is **_web3.providers.HttpProvider('http://localhost:8545')_** 
11. Whenever I attempt to do that command, I always **receive -bash: syntax error near unexpected token `'http://localhost:8545''**
12. apm link and apm install always seem to work fine

I've tried downloading the interface from the zip and from source multiple times each. I can never get #10 to work (the localhost) and I'm not sure really sure of the vi command. When I have gotten the interface to show up under packages in Atom, when I attempt to compile it says that its not connecting to my local geth host. I'm not sure what to do and could appreciate some help.

-Thank you

**Comment by 0mkara** [comment]
Please clone it in some directory other than atom.app, I think atom uses that directory for installed packages. Then do `apm link .` & `apm install`. Also you can install it using apm directly `apm install atom-ethereum-interface`, that just works fine. Let me know if your issue is resolved.
